default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: test123
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: change_my_info_development

dev:
  <<: *default
  database: change_my_info_dev

staging:
  <<: *default
  database: change_my_info_staging

production:
  <<: *default
  database: change_my_info_production

test:
  <<: *default
  database: change_my_info_test
